[project]
name = "what_was_year_about"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "nicegui",
    "gspread",
    "pandas",
    "gradio",
    "plotly",
    "groq",
    "scikit-learn",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
